'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Los cambios en este archivo podrían causar un comportamiento incorrecto.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Login

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    Protected WithEvents txtUsuario As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvUsuario As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label

    Protected WithEvents btnIngresar As Global.System.Web.UI.WebControls.Button
End Class
