'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Los cambios en este archivo podrían causar un comportamiento incorrecto.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Usuarios

    Protected WithEvents pnlMensaje As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents divMensaje As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label

    Protected WithEvents txtUsuario As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvUsuario As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents revPassword As Global.System.Web.UI.WebControls.RegularExpressionValidator

    Protected WithEvents txtConfirmar As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents cvPassword As Global.System.Web.UI.WebControls.CompareValidator

    Protected WithEvents btnCrear As Global.System.Web.UI.WebControls.Button

    Protected WithEvents gvUsuarios As Global.System.Web.UI.WebControls.GridView
End Class
