'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Los cambios en este archivo podrían causar un comportamiento incorrecto.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Bitacora

    Protected WithEvents gvBitacora As Global.System.Web.UI.WebControls.GridView
End Class
