'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Los cambios en este archivo podrían causar un comportamiento incorrecto.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Clientes

    Protected WithEvents pnlMensaje As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents divMensaje As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblTituloForm As Global.System.Web.UI.WebControls.Label

    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

    Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents rfvNombre As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents txtApellido As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtIdentificacion As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents revEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    Protected WithEvents txtTelefono As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents txtDireccion As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button

    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    Protected WithEvents gvClientes As Global.System.Web.UI.WebControls.GridView
End Class
